services:
  nginx:
    image: nginx-nexusproxy
    ports:
      - '443:443'
      - '5000:5000'
    links:
      - nexus
    command: [ nginx, '-g', 'daemon off;' ]
    networks:
     - nexus

  nexus:
    image: sonatype/nexus3:3.76.1
    container_name: nexus
    volumes:
    - nexus-data:/nexus-data
    networks:
    - nexus

volumes:
   nexus-data:

networks:
  nexus:
